### ISSUE TITLE
aplpy crashing in MuseCube class

### ISSUE THREAD

**Issue by TrystanScottLambert** [ismaelpessa/Muse_Cube#71]
In the main muse cube class there is a line:  
 ```python
self.gc2 = aplpy.FITSFigure(self.filename_white, figure=plt.figure(self.n))
```
But wouldn't it be necessary to included slices=[1] or some other channel number? The code will crash because the dimensions of the wcs of the fits cube is three whilst aplpy.FITSFigure plots a 2D plot.

**Comment by ismaelpessa** [comment]
Hi Trystan,
Thanks for your message.  It is not needed because self.filename_white is created  by the load_data() function (if no white image is provided).
 If provided, through the filename_white variable, it should be 2D already (otherwise it will crash). 
Make sure that you provide a 2D fitsfile image to the filename_white variable, or alternatively, try just initializing the object with the cube file instead.
Hope this helps, let me know if you find any other issue.
Cheers,


Cheers,

Ismael

**Comment by TrystanScottLambert** [comment]
Thanks for the quick reply. I'm not sure what might be causing the crash but when we don't include a white image it crashes because of the aply.FITSFigure and slices. So I'm not sure if the white image is being produced correctly. Also when we try include a 2D white image ourselves the line:

```python
self.white_data = fits.open(self.filename_white)[1].data
```
crashes because of the 1 indexing. Is it a good idea to assume that the hdu list of the white image has to be at the first index? We created the white image using CARTA which results in an hdulist of just one value.

**Comment by ismaelpessa** [comment]
That is true, assuming that the white image is in the hdu [1] is probably not the best, as in some cases might be a trouble. 
On the other hand, it should not be a problem, as initializing without providing a white image should generate an adequate white image, collapsing the MUSE cube.
Can you tell me what is the error you get when you dont provide an input white image, and how are you initializing the cube?

**Comment by TrystanScottLambert** [comment]
It crashes at line 87, the first line I quoted, and has a ValueError: 'slices' should have as many elements as WCS has pixel dimensions (should be 3). That error comes from the aplpy package, specifically the FITSFigure class.

**Comment by ismaelpessa** [comment]
And how are you initializing the MuseCube object when you get this error?

**Comment by TrystanScottLambert** [comment]
```python
from pyMUSE.musecube import MuseCube
MuseCube('Data_Cube.fits')
```

**Comment by ismaelpessa** [comment]
Ok. So, the error  seems to indicate that the filename_white contains something that is not 2D.
When you initialize in that way. A file named 'new_white.fits' should be created, that contains the white image in the hdu 1. Can you check what does new_white.fits looks like (i.e., is it actually a 2D image)?
Also, check if its header has any keywords relative to the third dimension. In principle, lines 113-133 correct the header of the new_white.fits, to be read as a 2D image  by aplpy. But maybe there is something else that was not removed for some reason, causing that aplpy thinks it is a cube .

**Comment by TrystanScottLambert** [comment]
new_white.fits is seems to be 2D. The header looks fine too. Not sure why it would be crashing.

XTENSION= 'IMAGE   '           / Image extension                                
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                    
NAXIS1  =                  325                                                  
NAXIS2  =                  316                                                  
PCOUNT  =                    0 / number of parameters                          
GCOUNT  =                    1 / number of groups                              
WCSAXES =                    3 / Number of coordinate axes                      
CRPIX1  =       164.3723113562 / Pixel coordinate of reference point            
CRPIX2  =      157.00287945926 / Pixel coordinate of reference point            
CUNIT1  = 'deg'                / Units of coordinate increment and value        
CUNIT2  = 'deg'                / Units of coordinate increment and value        
CTYPE1  = 'RA---TAN'           / Right ascension, gnomonic projection          
CTYPE2  = 'DEC--TAN'           / Declination, gnomonic projection              
CRVAL1  =      341.53147116381 / [deg] Coordinate value at reference point      
CRVAL2  =     -5.4430010251601 / [deg] Coordinate value at reference point      
LONPOLE =                180.0 / [deg] Native longitude of celestial pole      
LATPOLE =     -5.4430010251601 / [deg] Native latitude of celestial pole        
CSYER1  =    1.69760864415E-05 / [deg] Systematic error in coordinate          
CSYER2  =    6.54379526381E-06 / [deg] Systematic error in coordinate          
MJDREF  =                  0.0 / [d] MJD of fiducial time                      
RADESYS = 'FK5'                / Equatorial coordinate system                  
EQUINOX =               2000.0 / [yr] Equinox of equatorial coordinates        
CD1_1   = -5.5555555555556E-05                                                  
CD1_2   =                  0.0                                                  
CD2_1   =                  0.0                                                  
CD2_2   =  5.5555555555556E-05                                                  
OBJECT  = 'W2246-0526'                                                          
BUNIT   = '10**-20 Angstrom-1 cm-2 erg s-1' / data unit type                    
EXTNAME = 'DATA    '           / extension name                                
END

**Comment by ismaelpessa** [comment]
Try manually modifying the WCSAXES keyword, and set it to 2.
It is strange, since line 133 is supposed to change it. But for some reason it didn't.
After changing it, provide the edited fitsfile when initializing the MuseCube object, and hopefully that should fix the problem.
Let me know how it goes!

Cheers

**Comment by TrystanScottLambert** [comment]
Found the problem. 

We used pip to install the package and line 133 is missing from that. Using this repo and setup.py wouldn't result in the error.
